name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Create dist archive
      run: |
        cd dist
        zip -r ../json-editor-dist.zip .
        cd ..
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "JSON Editor ${{ steps.get_version.outputs.VERSION }}" \
          --notes "## JSON Editor & Visualizer Release ${{ steps.get_version.outputs.VERSION }}
        
        ### 🚀 What's New
        - Multi-format data support (JSON, YAML, CSV, XML, TOML)
        - Interactive visualizations (Tree, Card, Graph views)
        - File upload with drag-and-drop functionality
        - Dark/Light theme support
        - Monaco Editor integration
        - Export capabilities
        
        ### 📦 Download
        Download the \`json-editor-dist.zip\` file below and extract it to serve the application locally or deploy to any web server.
        
        ### 🌐 Quick Start
        1. Download and extract \`json-editor-dist.zip\`
        2. Serve the files using any web server:
           - Python: \`python -m http.server 8000\`
           - Node.js: \`npx serve .\`
           - PHP: \`php -S localhost:8000\`
        3. Open http://localhost:8000 in your browser
        
        ### 🔧 Technical Details
        - Built with Vue 3 + TypeScript + Vite
        - Optimized production build
        - All dependencies bundled
        - Works offline after initial load
        
        ### 🌐 Live Demo
        Try it live at: https://hypnguyen1209.github.io/json-editor/" \
          json-editor-dist.zip
